# Generated by Django 4.0.3 on 2022-04-08 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='text_info',
            new_name='text',
        ),
    ]
