# Generated by Django 4.0.3 on 2022-04-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
