# Generated by Django 4.0.3 on 2022-04-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_text_info_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
